### ISSUE TITLE
Sometimes Shairport-sync doesn't appear

### ISSUE THREAD

**Issue by gburkell** [mikebrady/shairport-sync#1052]
Sometimes when I go to connect from a device to listen to music the shairport-sync option doesn't appear in the Airplay list.  I'll reopen the app, close it, reboot the phone or device and it doesn't seem to see it, then later it'll be back. Has anyone had this issue before?

I'm on a Raspberry Pi 3.

**Comment by mikebrady** [comment]
Thanks for the post. This might be caused by many things, such as WiFi power management or by network problems. There's a good bit on information on the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page.

**Comment by gburkell** [comment]
Thanks Mike, Testing this out, I'll keep you guys posted.

**Comment by phexian** [comment]
I am having the same issue even after taking the steps in troubleshooting. It happens rather irregularly though.

**Comment by gburkell** [comment]
@phexian Ya, I'm working through those steps this week whenever I get a few minutes, but so far it isn't looking good. I feel it's something to do with wifi, but the wifi is pretty amazing where I am currently.

I'm currently doing this through two devices, one Raspberry Pi Zero and the other a Raspberry Pi 3.  What are you using?

**Comment by phexian** [comment]
Raspberry Pi Zero (with separate wifi adapter and PHAT DAC)

**Comment by phexian** [comment]
Also it is apparently an older version: 3.2 . I have installed shairport with the Pimoroni how-to. Is there anything I have to pay attention to while updating?

**Comment by mikebrady** [comment]
Nothing major. Just pay attention to cleaning up the old settings files – there's a guide at [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md).

**Comment by phexian** [comment]
I am a bit confused with one the first sentences: "If you wish to build an installation of Shairport Sync to replace an installation that came from a package, this doesn't really apply – instead, please follow the guide at INSTALL.md." Is http://get.pimoroni.com/airdac such a package?

**Comment by mikebrady** [comment]
Thanks for the post.

Yeah, the AirDac installation is just such a package.

The thing is, if you install Shairport Sync using the instructions on this repository, what you are doing is building it locally, on the machine, from the source files. To do this, you’ll have downloaded the source files themselves, the setting files and scripts and all the building tools. OTOH, when you install from a package, you just download the binary application itself along with the settings files and scripts.

Another difference is that the location of the application may be different, depending on whether is is installed from a package or built locally.

Finally, the settings and scripts can be subtly different.

So, if you are moving from an installed version to a locally-built version, it’s important to clean everything up first, as detailed in the INSTALL.md page. It’s not particularly daunting; you just need to pay close attention to every detail.

**Comment by phexian** [comment]
The install page does not mention Raspberry Pi Zero. Anything I should pay attention to specifically?

**Comment by mikebrady** [comment]
Nothing special. I use the Pi Zero W myself. As with all WiFi, though, ensure power management is off.

**Comment by phexian** [comment]
I keep having issues. Though I usually just cut the power to turn off the Raspi and I don't have power save mode off permanently. The troubleshooting part just changes till the next reboot, no? Also I am not sure how I set up the start delay file last time and have almost no experience with Terminal...

**Comment by mikebrady** [comment]
Thanks. Maybe if you could explain the issues a bit more it would be useful. I use a pi zero in a car where the power is cut without warning at the end of a journey and so far so good — two years. You should turn WiFi power management off permanently — you won’t notice the energy consumption difference and the service will be much more reliable.

**Comment by phexian** [comment]
Sorry. I'll observe it over the coming weeks. Sometimes I am not sure whether the device does not show up in the network altogether or if it is a specific Shairport issue. I implemented the power save off configuration and the delayed start and will give feedback whether this has helped.

**Comment by phexian** [comment]
So right now it does not connect to WLAN. Which is obviously not a Shairport issue. Any recommendations how I can check for causes though?

**Comment by mikebrady** [comment]
Thanks for the update. TBH, I've slightly lost track of the situation. So, if you just want Shairport Sync on your Pi 3, would you consider installing [Raspberry Pi OS](https://www.raspberrypi.org/downloads/raspberry-pi-os/)  and then installing Shairport Sync from here? That way, everything would be up to date and there wound not be any hidden issues.

**Comment by MichalKormanik** [comment]
I have similar problem. I've got Raspberry Pi 4 with Raspbian connect with wifi on network, turned off wifi power management and it still randomly disappear and reappear at all devices (MacBook Pro, Air, iMac, iPhone etc.)I tried also to disable 5 GHz wifi to use only 2.4 GHz and did not helped, all of the blocking are disabled on the network and it's still the same.
I tried to reinstall it several times and did not helped. 
Any recommendations or troubleshooting i can do?

**Comment by mikebrady** [comment]
Thanks for the post. It would be helpful to know the version of Shairport Sync you are using — please see the [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) page. When the service disappears, you can check if it’s being advertised to the network using `avahi-browse` on the Pi. Then you can see if the service is visible on the Mac or iOS end using the “Discovery” app from TildeSoft. If it’s being advertised but not being seen, then it’s some kind of network issue. (I’m assuming that the Pi is connected to the network only one way, via WiFi or Ethernet but not both, and there is nothing like a VPN working.)

**Comment by MichalKormanik** [comment]
Thank you for early reply. I done all the things you said above. 
Version of Shairport Sync is`3.3.7rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`   
So with `avahi-browse` command i can see that it is advertised to the network. Unfortunately I can't see it with "Discovery" app on the MacBook.
It is connected to the WiFi, specifically to Ubiquiti UniFi Access Point and Edgerouter. I tried briefly find some issues with AirPlay on UniFi and EdgeOS and tried some but doesn't work. 

Do you have any tips what can be cause this?

Thank you.

**Comment by mikebrady** [comment]
Thanks. I use an Ubiquiti UniFi Access Point myself with no problems -- really good gear. I don't, however, use an EdgeRouter, but only because I have been using another one based on pfSense.

So, I'd be looking at something associated with the network. Is there a firewall somewhere, on a device or on the router, that is blocking stuff (see the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) page)?

**Comment by MichalKormanik** [comment]
I enabled mDNS so i will test it now. Firewall is only basic for now (i didn't have enough time for really get deep into that) and it blocks mainly from WAN in and out so it has nothing to do with this. 

Thank you for your fast answers. When i'll solve it i can report what was wrong so others can solve it quicker.

Have a nice day! 👍

**Comment by MichalKormanik** [comment]
I've been testing it all weekend and mDNS helped. 

If someone has same problem check mDNS reflector settings.
