### ISSUE TITLE
4.0-dev-186 - rare crash in multi-room setup

### ISSUE THREAD

**Issue by acresp** [mikebrady/shairport-sync#1254]
Hello,
Since two weeks I use the dev version every day.
For the moment I only had 2 crashes, always with the same setup.

I play Spotify through AirPlay 2 to one room and then I want to add an extra room, running the same version of ShairPort Sync. I check the box, it's running fine and perfectly in sync for some minutes / hour (random). But then, no sound in the last added room. The room is not showing anymore in the AirPlay list. If I go to my Moode Audio I see that the "AirPlay is playing", If I force the disconnection, it's working again (but I don't know if when I force this disconnection it's restarting the shairport-sync instance...).

How can I debug that ? The /var/log/shairport-sync.log is empty.

As I said, I upgraded the Shairport-Sync of a MoOde Audio distribution, maybe there is some config related to that which are not totally "compliant" with the 4.0-dev version of Shairport-Sync.

**Comment by mikebrady** [comment]
Thanks for the post. It's good to hear that the development version is reasonably stable.

By default, the Shairport Sync log would be available via the standard `journalctl` facility in recent Linuxes. So, for example, you might see `shairport-sync` entries using the following commands:

```
$ sudo journalctl | grep shai
```
Again, by default, the configuration file for Shairport Sync would be at `/etc/shairport-sync.conf`. It would certainly be worth setting the `log_verbosity` to `1` Don't be tempted to use `2` or `3` -- they are too verbose at this point. Also, enabling `statistics` might be helpful. You need to restart Shairport Sync for the changes to take effect.

TBH, I don't really have a strong idea of what might be causing the problem. If you could get Shairport Sync to crash reliably, that would be ideal.

**Comment by acresp** [comment]
Thanks. I adapted my config and restarted the 2 zones. My second zone also crashed recently. No more shairport-sync in the process list (`ps aux`).

For the moment, the only thing I see in the log is:

`Jul 26 13:56:27 AudioTerrasse shairport-sync[26269]:       1273.233312969 "rtsp.c:832" Unrecognised SETUP incoming message
Jul 26 13:56:27 AudioTerrasse shairport-sync[26269]:          0.000177344 "rtsp.c:837"   Content Plist (as XML):
Jul 26 13:56:27 AudioTerrasse shairport-sync[26269]:          0.007779410 "rtsp.c:1599" pair-add cb for 8C898D32-7FA6-4602-9640-77771527684A
Jul 26 13:56:27 AudioTerrasse shairport-sync[26269]:          0.001056977 "rtsp.c:1627" pair-list cb`

Is it related to HomeKit ?

**Comment by mikebrady** [comment]
Very interesting! Yes indeed, I believe it is related to HomeKit.  As a matter of interest, was anything printed out after the second line and before the third line of the log above -- was some XML printed?

**Comment by acresp** [comment]
> Very interesting! Yes indeed, I believe it is related to HomeKit. As a matter of interest, was anything printed out after the second line and before the third line of the log above -- was some XML printed?

Hello Mike,
No XML printed

**Comment by mikebrady** [comment]
So, I've pushed an update that, hopefully, can cleanly ignore an "unrecognised" SETUP message and log a message and a warning. Up to now, it would simply crash. If I'm right, Shairport Sync shouldn't crash in the same circumstances and, hopefully, not at all. However, it may not work properly afterwards. So, whenever you got a chance to try it out and see if it makes any difference, it would be appreciated.

**Comment by acresp** [comment]
> So, I've pushed an update that, hopefully, can cleanly ignore an "unrecognised" SETUP message and log a message and a warning. Up to now, it would simply crash. If I'm right, Shairport Sync shouldn't crash in the same circumstances and, hopefully, not at all. However, it may not work properly afterwards. So, whenever you got a chance to try it out and see if it makes any difference, it would be appreciated.

Hi Mike,
Running correctly since this morning. The only thing strange is that I don't have anymore shairport-sync log in the journalctl.
The shairport-sync.conf is unchanged (still with statistics and verbosity to 1)

**Comment by mikebrady** [comment]
Thanks. I’ll have to check that log issue — I may have done something 🤔.

**Comment by mikebrady** [comment]
Regarding that log issue -- I was messing around and forgot to undo the hack. Just push an update that [I think!] fixes it.

**Comment by acresp** [comment]
> Regarding that log issue -- I was messing around and forgot to undo the hack. Just push an update that [I think!] fixes it.

It's ok now 👍 
I will continue the test and see If I still have these mysterious crashes.

**Comment by bloomkd46** [comment]
how can I install the 4.0-dev-186 software. I am really hoping to use it with homekit

**Comment by charlesomer** [comment]
There's a docker image available or please take a look at: https://github.com/mikebrady/shairport-sync/blob/development/BUILDFORAP2.md. HomeKit support is limited though at the moment

**Comment by bloomkd46** [comment]
Thank You

**Comment by bloomkd46** [comment]
I can't get it to work with a HomePod for multi-room, when I ran systemctl status shairport-sync if found this:
```
systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
shairport-sync[619]: warning: Unrecognised SETUP incoming message -- ignored.
shairport-sync[619]: warning: Unrecognised SETUP incoming message -- ignored.
shairport-sync[619]: warning: Unrecognised SETUP incoming message -- ignored.
shairport-sync[619]: warning: Unrecognised SETUP incoming message -- ignored
```

**Comment by charlesomer** [comment]
There are some situations that currently don't work: https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md

It might be a good idea to open a new issue with more information about your setup, are you using Apple Music, trying to stream from the HomePod to Shairport Sync etc.?
