### ISSUE TITLE
[Problem]: Docker no alsa device

### ISSUE THREAD

**Issue by Gibbz** [mikebrady/shairport-sync#1583]
### What happened?

No sound output on the docker image. Looks like it cant find alsa device...
Do I need to specify the device in the conf file? 
Is there a way to run with pulse audio?

### Relevant log output

```shell
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'

ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory

ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings

ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory

ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name

ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory

ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory

ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default

fatal error: the alsa output_device "default" can not be found.
```

### Configuration Information.

Linux s-pc 6.0.6-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 29 14:21:50 UTC 2022 x86_64 GNU/Linux

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Can you post the command you used to launch the Docker image, please?

**Comment by Gibbz** [comment]
Attached docker compose. Thanks

[shairport.zip](https://github.com/mikebrady/shairport-sync/files/10061477/shairport.zip)

**Comment by Gibbz** [comment]
Ive tried setting a few of the alsa options (output_device and mixer_control_name) in the config with no luck. It does change the errors to:

`
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card

fatal error: the alsa output_device "hw:0" can not be found.
`

**Comment by mikebrady** [comment]
Thanks. I wonder if it's a permissions issue with the Docker compose script.

If you try the [Docker image](https://hub.docker.com/r/mikebrady/shairport-sync) from the Docker Hub and use the standard command there to invoke it, does that fare any better? As you can see there, you can also add Shairport Sync options to the end of the command, including output device names. E.g.:
```
$ docker run -d --restart unless-stopped --net host --device /dev/snd \
    mikebrady/shairport-sync -a Manjaro -- -d hw:0,3
```

Another question -- did you build `sps-alsa-explore` or run it from [its own Docker image](https://hub.docker.com/r/mikebrady/sps-alsa-explore)? Again, it would be interesting to see whether is works when invoked using the commands there.

**Comment by Gibbz** [comment]
For alsa explorer i just use the command listed: 
docker run --device /dev/snd mikebrady/sps-alsa-explore

I have mycroft running fine on the same system but thats using pulse audio, and just works....

**Comment by Gibbz** [comment]
I'm getting the same errors with that command.
Is there a way to check the devices from within the shairport-sync docker container?

**Comment by Gibbz** [comment]
Ive managed to get amixer installed in the docker container. Heres the output:

```
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]

```

**Comment by Gibbz** [comment]
Ok managed to change default card to 2 using the info from https://wiki.alpinelinux.org/wiki/ALSA

then using espeak and aplay, it plays sound throught the container
```
espeak --stdout "this is a test" | aplay
```

so sound output is working fine from the container. But still have no sound from shairport-sync!

**Comment by mikebrady** [comment]
Thanks for the update.

In the present Docker image, Shairport Sync runs under the user with the ID `shairport-sync`, the same as in a regular installation. The idea is that the `shairport-sync` user has fewer privileges than the `root` superuser -- it's a weak security measure. However, it just might be interfering with access to the output devices.

So, I've just pushed an update in which Shairport Sync runs as the `root` superuser within the Docker container. In about an hour (it's now 11:39 Saturday, 26 November 2022 (UTC)) an updated Docker image should be available with the `development` tag in the Docker Hub. If you could give that a tryout, it might help.

**Comment by Gibbz** [comment]
That's fixed the errors, but i'm still not getting sound output from shairport.

I assume if i modify the alsa.conf with the default card to 2, i shouldn't need to specify the output device on the command line right?

Ive got a few ideas so will play with it again over the next few days.

**Comment by mikebrady** [comment]
Good stuff -- that's some kind of progress. Make sure the output DAC is unmuted and that the volume level is up -- by default Shairport Sync won't try to unmute and it doesn't know what mixer to use unless you tell it with a command line option or a setting in the settings file. The `alsamixer` utility is useful for checking.

> I assume if i modify the alsa.conf with the default card to 2, i shouldn't need to specify the output device on the command line right?

It shouldn't make a difference -- using the command line argument is the most direct. 

I meant to ask -- what is the host machine and OS?

**Comment by mikebrady** [comment]
Another thing has occurred to me:
* You should enable statistics on Shairport Sync. If it's processing audio, it should put out a line of statistics every 8 seconds or so.
* Do you have firewalls running? If so, open ports 320 and 319 to UDP in both directions.

**Comment by Gibbz** [comment]
Im runing manjaro on the host machine. Which is an amd apu system. No firewall.

Running the command:
```
docker run --restart unless-stopped --privileged --net host --device /dev/snd mikebrady/shairport-sync:development --statistics -a Manjaro -- -d hw:2,0

```

output:
```
Connection 1: Playback started at frame 1482634969 -- AirPlay 1 Compatible.
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
        -0.92          243.2          248.9         0             0              N/A              N/A
        -1.64          645.8          645.8         0             0         44126.34         44103.64
        -1.50          628.8          628.8         0             0         44129.09         44106.39
Connection 1: Playback stopped. Total playing time 00:00:29. Output: 44129.09 (raw), 44106.39 (corrected) frames per second.
```

The container can play sound when using aplay. But shirport-sync doesnt play any sound.... Any other ideas what may cause this issue?

**Comment by mikebrady** [comment]
Sorry about the delay in responding. The statistics indicate that Shairport Sync "thinks" it is outputting to an output device which is returning information about timing, etc. So it's as if the sound is being output to something, but is disappearing. It would be worth checking -- with something like `alsamixer` -- that the output devices are unmuted and that volume level are up.

Device 2 is the USB audio output, right?

What are you playing from please? Is it an iOS app?

**Comment by Gibbz** [comment]
Im playing from double twist, an android app.
speaker-test from the container command line plays sound fine so alsa is working, and not muted.

Ive tried it on a second system now, and have exactly the same issue.

Where are the files for the app located in the container? Can i try run it manually form the command line to see if that helps?

**Comment by mikebrady** [comment]
If you `-exec` into the container, you can use `which` to find the apps. For example:
```
$ docker exec -it <name_of_running_shairport_sync_container> sh
/ # which shairport-sync
/usr/local/bin/shairport-sync
```
(Note, the image does not contain `bash`, just `sh`.)

The big problem here is that if you kill `shairport-sync`, the container will terminate (this is deliberate).

Three things.

1. My slight experience with Android AirPlay apps is that they are generally pretty idiosyncratic and somewhat unreliable. Also, they usually they have quite inaccurate clocks. In your statistics logs, the level of interpolation -- `645.8 PPM` -- is very high; typically that would be down in the low 10s, and is often 0.0 when the source is an iOS or macOS app.
2. Double Twist produces classic AirPlay and not AirPlay 2, so you might wish to try the classic variant of the Shairport Sync Docker image -- to do that, just run the image tagged `classic` rather than `latest`. 
3. Would you consider just building Shairport Sync itself on the platform, i.e. not using the Docker image? The advantage of this would be to ensure that it's running properly and producing output without having to be concerned about any Docker issues.

**Comment by Gibbz** [comment]
I'll try an iPhone when I get a chance. Then look at running the native version. 

I'd like to stick to the docker container if I can get it working.

**Comment by Gibbz** [comment]
Ive managed to get it working! Iphone and doubletwist work fine :)
After some research, i read that alsa does not support multiple audio sources. So ive disabled all other containers which use alsa, and use shairport purely from alsa and its now working!

Do you think its possible to add pulse audio support to the docker image in the future?

**Comment by mikebrady** [comment]
That's great news -- well done! (Also, I am sorry I didn't think of it as a possible issue. Next time!)

@noelhibbard has done quite a bit of work on PulseAudio in Docker.

**Comment by Gibbz** [comment]
great thanks for your help!
