### ISSUE TITLE
Beginner issue, failed to attach mixer

### ISSUE THREAD

**Issue by jebej** [mikebrady/shairport-sync#231]
Hello,

I am trying to set up shairport-sync on a netbook running Ubuntu server 14.04.

I am having trouble getting shairport to start. I have tried listing the cards/mixers/devices (not sure what the correct terminology is here...) by using amixer.

I would like to output sound through the headphone port, and so the relevant entry after running `amixer` seems to be:

```
Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 64
  Mono:
  Front Left: Playback 60 [94%] [-3.00dB] [on]
  Front Right: Playback 60 [94%] [-3.00dB] [on]
```

I am guessing that I need to set `mixer_control_name` to `Headphone`, but do not know what to set `output_device` to. I have tried `output_device=hw:0`, `output_device=HDA-Intel` and a few more.

I every case, I get the following error (with the corresponding output device name):

```
Output device name is "HDA-Intel".
Open Mixer
Mixer device name is "HDA-Intel".
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL HDA-Intel
Failed to attach mixer
```

I am not sure how to proceed from here, would you be able to help me?
Thanks,
Jeremy

**Comment by mikebrady** [comment]
Hi there. Thanks for your interest in Shairport Sync. 

The word `mixer` is a bit of misnomer, IMHO, as it's really a volume control – it doesn't mix, say, sound coming from two sources.

If you use `alsamixer` you'll see a list of the output devices. If you select the one you want it and select it you'll see the mixer name associated with it, e.g. Headphone. If you then try to select another device and use the 'enter device name..' selection, you'll be prompted with the device name of the device you're just about to leave, e.g. "hw:1".

So, your output device will be something like `hw:0` and the mixer name will be something like `Headphone` or `PCM`.

**Comment by jebej** [comment]
Thanks for your reply. I'm having a bit of trouble understanding the instructions here. If I select the Headphone device, press F6, and then `enter device name...` the name that appears is `default`. I see no mention of `PCM` anywhere.

If I do put `output_device=default` in the conf file the same problem I had before occurs...

**Comment by jebej** [comment]
Could this have to do with the fact that I am using Ubuntu server?

**Comment by mikebrady** [comment]
I'm afraid I don't know. Does it work with default settings? (But use alsa mixer to set the output volume to max.)

**Comment by ashwinvandijk** [comment]
I got the same issue some days ago. I fixed it by commenting the mixer-setting in the config-file.

**Comment by mikebrady** [comment]
Just looking at this again. Quotation marks are important. Where you wrote:
```
output_device=default
```
It should have been:
```
output_device="default";
```

**Comment by mikebrady** [comment]
Hi there. Did you make any progress with this? Is it okay to close the issue?

**Comment by jebej** [comment]
I'm not getting any failed to attach mixer error anymore by putting the output_device back to default but still not getting any sound...

I was surprised because I am pretty sure I had tried with the default. Honestly, I tried a bunch of things like trying to configure ALSA etc and that might have fixed the mixer not attached problem.

**Comment by mikebrady** [comment]
Thanks for the update. Have you tried using `alsamixer` toadjust the volume?

**Comment by rstackhouse** [comment]
Hello, I see this error in the daemon.log file on Raspbian Jessie if I try to start shairport-sync as a service, but not if I start it from the command line.

Any idea why?

I was thinking that maybe the service is missing a dependency.

**Comment by rstackhouse** [comment]
If I modify the service definition to pass the -vvv option to shairport-sync, I see the following:

```
Jan 15 20:33:17 <hostname> systemd[1]: Starting ShairportSync AirTunes receiver...
Jan 15 20:33:17 <hostname> systemd[1]: Started ShairportSync AirTunes receiver.
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Looking for the configuration file "/etc/shairport-sync.conf".
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Looking for configuration file at full path "/etc/shairport-sync.conf"
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Output device name is "default".
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Open Mixer
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Mixer device name is "default".
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Failed to attach mixer
Jan 15 20:33:17 <hostname> shairport-sync[1136]: Request to shut down all rtsp conversation threads
Jan 15 20:33:17 <hostname> shairport-sync[1136]: asking playing threads to stop

```

**Comment by rstackhouse** [comment]
Saw the same message, but it was a permissions problem. The service definition says that the executable should be run as the user shairport-sync in the group shairport-sync. Adding the shairport-sync user to the audio group (on Raspbian Jessie) fixed the issue.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
